### ISSUE TITLE
Mostrar las características a seleccionar en una moto (Hito - 20 de abril)

### ISSUE THREAD

**Issue by raquelcedazo** [aigora/twQ103_1920-twq103-devil_engine#1]
Hola:

Os comento lo que veo de vuestra primera entrega y os propongo añadirle más funcionalidad.

El código está bastante desorganizado y cuesta leerlo. Varias cosas: el fichero debe tener extensión .c; las variables deben declararse todas juntas al comienzo del programa, no por medio; el menú debe mostrarse en un bucle para que se repita.

Además, debéis describir en el archivo principal los "Objetivos del trabajo" con el detalle de cada una de las funcionalidades. Realmente no sé cuántas cosas va a hacer vuestro programa. Enumeradlas por favor. 

El hito que os propongo para el 20 de abril es que creéis un fichero de texto (.txt) con todos los datos de las características que se podrían utilizar y se muestre por pantalla cuando se pulse la opción correspondiente. Os aconsejo que almacenéis los datos en un vector de estructuras.

Además de esto, os animo a que sigáis programando más funcionalidades, como la de seleccionar las diferentes características, etc. 

Un saludo y buenas vacaciones.

**Comment by Virus-exe-sys** [comment]
Ya hemos realizado con éxito el hito propuesto
